module.exports = [
"[project]/src/app/opengraph-image--metadata.js [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/src/app/opengraph-image--metadata.js [app-rsc] (ecmascript)"));
}),
"[externals]/next/dist/shared/lib/no-fallback-error.external.js [external] (next/dist/shared/lib/no-fallback-error.external.js, cjs)", ((__turbopack_context__, module, exports) => {

const mod = __turbopack_context__.x("next/dist/shared/lib/no-fallback-error.external.js", () => require("next/dist/shared/lib/no-fallback-error.external.js"));

module.exports = mod;
}),
"[project]/src/app/global-error.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/src/app/global-error.tsx [app-rsc] (ecmascript)"));
}),
"[project]/src/app/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/src/app/layout.tsx [app-rsc] (ecmascript)"));
}),
"[project]/src/app/template.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/src/app/template.tsx [app-rsc] (ecmascript)"));
}),
"[project]/src/app/not-found.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/src/app/not-found.tsx [app-rsc] (ecmascript)"));
}),
"[project]/src/app/portfolio/PortfolioClient.tsx [app-rsc] (client reference proxy) <module evaluation>", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "default",
    ()=>__TURBOPACK__default__export__
]);
// This file is generated by next-core EcmascriptClientReferenceModule.
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f2e$pnpm$2f$next$40$16$2e$1$2e$5_$40$babel$2b$core$40$7$2e$28$2e$6_$40$opentelemetry$2b$api$40$1$2e$9$2e$0_$40$playwright$2b$test$40$1$2e$58$2e$0_react$2d$d_da4cc879827f7917e183558a349a788d$2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/.pnpm/next@16.1.5_@babel+core@7.28.6_@opentelemetry+api@1.9.0_@playwright+test@1.58.0_react-d_da4cc879827f7917e183558a349a788d/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const __TURBOPACK__default__export__ = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f2e$pnpm$2f$next$40$16$2e$1$2e$5_$40$babel$2b$core$40$7$2e$28$2e$6_$40$opentelemetry$2b$api$40$1$2e$9$2e$0_$40$playwright$2b$test$40$1$2e$58$2e$0_react$2d$d_da4cc879827f7917e183558a349a788d$2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call the default export of [project]/src/app/portfolio/PortfolioClient.tsx <module evaluation> from the server, but it's on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/src/app/portfolio/PortfolioClient.tsx <module evaluation>", "default");
}),
"[project]/src/app/portfolio/PortfolioClient.tsx [app-rsc] (client reference proxy)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "default",
    ()=>__TURBOPACK__default__export__
]);
// This file is generated by next-core EcmascriptClientReferenceModule.
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f2e$pnpm$2f$next$40$16$2e$1$2e$5_$40$babel$2b$core$40$7$2e$28$2e$6_$40$opentelemetry$2b$api$40$1$2e$9$2e$0_$40$playwright$2b$test$40$1$2e$58$2e$0_react$2d$d_da4cc879827f7917e183558a349a788d$2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/.pnpm/next@16.1.5_@babel+core@7.28.6_@opentelemetry+api@1.9.0_@playwright+test@1.58.0_react-d_da4cc879827f7917e183558a349a788d/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const __TURBOPACK__default__export__ = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f2e$pnpm$2f$next$40$16$2e$1$2e$5_$40$babel$2b$core$40$7$2e$28$2e$6_$40$opentelemetry$2b$api$40$1$2e$9$2e$0_$40$playwright$2b$test$40$1$2e$58$2e$0_react$2d$d_da4cc879827f7917e183558a349a788d$2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call the default export of [project]/src/app/portfolio/PortfolioClient.tsx from the server, but it's on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/src/app/portfolio/PortfolioClient.tsx", "default");
}),
"[project]/src/app/portfolio/PortfolioClient.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$app$2f$portfolio$2f$PortfolioClient$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__$3c$module__evaluation$3e$__ = __turbopack_context__.i("[project]/src/app/portfolio/PortfolioClient.tsx [app-rsc] (client reference proxy) <module evaluation>");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$app$2f$portfolio$2f$PortfolioClient$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__ = __turbopack_context__.i("[project]/src/app/portfolio/PortfolioClient.tsx [app-rsc] (client reference proxy)");
;
__turbopack_context__.n(__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$app$2f$portfolio$2f$PortfolioClient$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__);
}),
"[project]/src/lib/supabase/urls.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "buildSupabaseStorageUrl",
    ()=>buildSupabaseStorageUrl,
    "getSupabaseBaseUrl",
    ()=>getSupabaseBaseUrl,
    "normalizeStoragePath",
    ()=>normalizeStoragePath,
    "validateExternalUrl",
    ()=>validateExternalUrl
]);
const normalizeUrl = (value)=>value.replace(/\/+$/, '');
// Fallback alinhado ao projeto Ghost Era (umkmwbkwvulxtdodzmzf)
const DEFAULT_SUPABASE_URL = 'https://umkmwbkwvulxtdodzmzf.supabase.co';
function getSupabaseBaseUrl() {
    const url = ("TURBOPACK compile-time value", "https://umkmwbkwvulxtdodzmzf.supabase.co") ?? process.env.SUPABASE_URL ?? ("TURBOPACK compile-time value", "https://umkmwbkwvulxtdodzmzf.supabase.co") ?? DEFAULT_SUPABASE_URL;
    if ("TURBOPACK compile-time falsy", 0) //TURBOPACK unreachable
    ;
    try {
        return normalizeUrl(url);
    } catch  {
        return url;
    }
}
function normalizeStoragePath(filePath, bucket) {
    if (!filePath) return null;
    const bucketPrefix = bucket?.replace(/^\/+|\/+$/g, '');
    // Remove full Supabase URL prefix if present (object or render endpoints)
    let normalized = filePath.trim();
    // Clean common malformed prefixes/suffixes from backups (e.g. "file_path: ...," or quoted values)
    normalized = normalized.replace(/^file_path:\s*/i, '');
    normalized = normalized.replace(/^key:\s*/i, '');
    normalized = normalized.replace(/^"+|"+$/g, '');
    normalized = normalized.replace(/^'+|'+$/g, '');
    normalized = normalized.replace(/,+$/g, '');
    normalized = normalized.replace(/\s+$/g, '');
    normalized = normalized.replace(/^https?:\/\/[^/]+\/storage\/v1\/(?:render\/image|object)\/public\//, '');
    // Remove local /storage/v1/object/public prefix if the path was stored like that
    normalized = normalized.replace(/^\/?storage\/v1\/(?:render\/image|object)\/public\//, '');
    normalized = normalized.replace(/^\/+/, '');
    if (bucketPrefix && normalized.startsWith(`${bucketPrefix}/`)) {
        normalized = normalized.slice(bucketPrefix.length + 1);
    }
    return normalized;
}
function buildSupabaseStorageUrl(bucket, filePath) {
    if (!filePath) return null;
    const isHttp = filePath.startsWith('http://') || filePath.startsWith('https://');
    const isSupabaseUrl = filePath.includes('/storage/v1/');
    // Verifica se é uma URL externa não-Supabase
    if (isHttp && !isSupabaseUrl) {
        // Validação de segurança para URLs externas
        try {
            const url = new URL(filePath);
            // Permitir apenas protocolos seguros
            if (url.protocol !== 'https:') {
                console.warn(`Protocolo inseguro detectado: ${filePath}`);
                return null;
            }
            // Aqui poderíamos adicionar validação de domínio se necessário
            return filePath;
        } catch  {
            console.error(`URL inválida: ${filePath}`);
            return null;
        }
    }
    const cleanBucket = bucket.replace(/^\/+|\/+$/g, '');
    const normalizedPath = normalizeStoragePath(filePath, cleanBucket);
    if (!normalizedPath) {
        return filePath.startsWith('http') ? filePath : null;
    }
    // Preserva a origem caso o caminho já seja uma URL completa de outro projeto Supabase
    if (isHttp && isSupabaseUrl) {
        try {
            const url = new URL(filePath);
            const baseOrigin = `${url.protocol}//${url.host}`;
            return `${baseOrigin}/storage/v1/object/public/${cleanBucket}/${normalizedPath}`;
        } catch  {
        // se falhar, segue fluxo padrão
        }
    }
    const baseUrl = getSupabaseBaseUrl();
    if (!baseUrl) {
        return filePath.startsWith('http') ? filePath : null;
    }
    return `${baseUrl}/storage/v1/object/public/${cleanBucket}/${normalizedPath}`;
}
function validateExternalUrl(url) {
    if (!url) return null;
    const normalized = url.trim();
    if (!normalized) return null;
    const allowedProtocols = [
        'https:',
        'http:'
    ];
    try {
        const parsedUrl = new URL(normalized);
        if (allowedProtocols.includes(parsedUrl.protocol)) {
            return parsedUrl.toString();
        }
        console.warn(`Link externo inseguro bloqueado: ${url}`);
        return null;
    } catch  {
        if (normalized.startsWith('/') || normalized.startsWith('#')) {
            return normalized;
        }
        if (normalized.startsWith('//')) {
            try {
                const parsedFallback = new URL(`https:${normalized}`);
                return parsedFallback.toString();
            } catch  {
                console.error(`URL externa inválida: ${url}`);
                return null;
            }
        }
        console.error(`URL externa inválida: ${url}`);
        return null;
    }
}
}),
"[project]/src/lib/portfolio/project-mappers.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "mapDbProjectToPortfolioProject",
    ()=>mapDbProjectToPortfolioProject,
    "mapStaticProjectToPortfolioProject",
    ()=>mapStaticProjectToPortfolioProject
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$supabase$2f$urls$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/lib/supabase/urls.ts [app-rsc] (ecmascript)");
;
const CATEGORY_MAP = {
    'Branding & Identity': 'branding',
    'Campanhas & Advertising': 'campanha',
    Campanha: 'campanha',
    Branding: 'branding',
    'Web & Digital': 'web',
    'Motion & Video': 'motion',
    'Institucional & Retail': 'institucional',
    Packaging: 'packaging'
};
const ACCENT_COLOR_MAP = {
    branding: '#0057ff',
    campanha: '#ff3366',
    web: '#4fe6ff',
    motion: '#8705f2',
    institucional: '#00a868',
    packaging: '#ffd700',
    all: '#ffffff'
};
function getProjectCategory(projectType) {
    if (!projectType) return 'branding';
    const normalized = projectType.trim();
    return CATEGORY_MAP[normalized] ?? 'branding';
}
function determineProjectType(project) {
    if ('featured_on_home' in project) {
        // It's a DbProjectWithTags
        if (project.featured_on_home || project.featured_on_portfolio) {
            return 'A';
        }
    }
    // For StaticProject, or if not featured, default to 'B'
    // You might want to refine this logic based on your static data structure
    return 'B';
}
function buildLayout(projectType, index) {
    /**
   * Layout Pattern para Portfolio Grid:
   * - Rows devem sempre somar 12 colunas (edge-to-edge)
   * - Altura fixa no desktop para uniformidade visual
   * - Pattern: [5+7], [7+5], [4+4+4], [6+6], [8+4], [4+8]
   */ const pairedLayouts = [
        // Row pattern: 5 + 7 = 12
        {
            cols: 'md:col-span-5 lg:col-span-5',
            height: 'min-h-[320px]',
            aspectRatio: 'aspect-[4/5]',
            sizes: '(max-width: 768px) 100vw, (max-width: 1200px) 42vw, 42vw'
        },
        {
            cols: 'md:col-span-3 lg:col-span-7',
            height: 'min-h-[320px]',
            aspectRatio: 'aspect-[4/5]',
            sizes: '(max-width: 768px) 100vw, (max-width: 1200px) 58vw, 58vw'
        },
        // Row pattern: 7 + 5 = 12
        {
            cols: 'md:col-span-5 lg:col-span-7',
            height: 'min-h-[320px]',
            aspectRatio: 'aspect-[4/5]',
            sizes: '(max-width: 768px) 100vw, (max-width: 1200px) 58vw, 58vw'
        },
        {
            cols: 'md:col-span-3 lg:col-span-5',
            height: 'min-h-[320px]',
            aspectRatio: 'aspect-[4/5]',
            sizes: '(max-width: 768px) 100vw, (max-width: 1200px) 42vw, 42vw'
        },
        // Row pattern: 4 + 4 + 4 = 12 (3 cards per row)
        {
            cols: 'md:col-span-4 lg:col-span-4',
            height: 'min-h-[320px]',
            aspectRatio: 'aspect-[4/5]',
            sizes: '(max-width: 768px) 100vw, (max-width: 1200px) 33vw, 33vw'
        },
        {
            cols: 'md:col-span-4 lg:col-span-4',
            height: 'min-h-[320px]',
            aspectRatio: 'aspect-[4/5]',
            sizes: '(max-width: 768px) 100vw, (max-width: 1200px) 33vw, 33vw'
        },
        {
            cols: 'md:col-span-4 lg:col-span-4',
            height: 'min-h-[320px]',
            aspectRatio: 'aspect-[4/5]',
            sizes: '(max-width: 768px) 100vw, (max-width: 1200px) 33vw, 33vw'
        },
        // Row pattern: 6 + 6 = 12 (2 equal cards)
        {
            cols: 'md:col-span-4 lg:col-span-6',
            height: 'min-h-[320px]',
            aspectRatio: 'aspect-[4/5]',
            sizes: '(max-width: 768px) 100vw, 50vw'
        },
        {
            cols: 'md:col-span-4 lg:col-span-6',
            height: 'min-h-[320px]',
            aspectRatio: 'aspect-[4/5]',
            sizes: '(max-width: 768px) 100vw, 50vw'
        }
    ];
    // Para projetos do tipo A (featured), usar layouts variados
    // Para tipo B, usar grid uniforme de 4 colunas
    if (projectType === 'A') {
        const layoutIndex = index % pairedLayouts.length;
        return pairedLayouts[layoutIndex];
    }
    // Projetos tipo B: sempre 4 colunas (3 por linha no lg)
    return {
        cols: 'md:col-span-4 lg:col-span-4',
        height: 'min-h-[320px]',
        aspectRatio: 'aspect-[4/5]',
        sizes: '(max-width: 768px) 100vw, (max-width: 1200px) 33vw, 33vw'
    };
}
function toTagsList(tags) {
    if (!tags) return [];
    if (typeof tags[0] === 'string') {
        return tags;
    }
    return tags?.map((entry)=>entry?.tag?.label ?? entry?.tag?.slug).filter(Boolean).map((value)=>value) ?? [];
}
function createGallery(project) {
    const entries = project.gallery ?? [];
    return entries.filter((entry)=>!!entry).map((entry)=>entry.path).filter((path)=>!!path).map((path)=>(0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$supabase$2f$urls$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["buildSupabaseStorageUrl"])('portfolio-media', path)).filter((url)=>!!url); // Additional filter to remove any null urls from buildSupabaseStorageUrl
}
function toVideoPreview(galleryUrls) {
    const videoExt = [
        'mp4',
        'mov',
        'webm',
        'm4v'
    ];
    return galleryUrls.find((url)=>{
        const extension = url.split('.').pop()?.toLowerCase();
        return extension ? videoExt.includes(extension) : false;
    }) ?? undefined;
}
function mapDbProjectToPortfolioProject(project, index) {
    const type = determineProjectType(project);
    const layout = buildLayout(type, index);
    const category = getProjectCategory(project.project_type);
    const tags = toTagsList(project.tags);
    const gallery = createGallery(project);
    const thumbnailUrl = (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$supabase$2f$urls$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["buildSupabaseStorageUrl"])('portfolio-media', project.thumbnail_path ?? undefined) || (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$supabase$2f$urls$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["buildSupabaseStorageUrl"])('portfolio-media', project.hero_image_path ?? undefined);
    const detail = {
        description: project.description ?? '',
        highlights: tags.length ? tags.slice(0, 3) : undefined,
        gallery
    };
    return {
        id: project.id,
        slug: project.slug,
        title: project.title,
        subtitle: project.short_label ?? project.client_name,
        client: project.client_name,
        category,
        displayCategory: project.project_type ?? 'Web',
        tags,
        year: project.year ?? 0,
        image: thumbnailUrl || '',
        type,
        layout,
        detail,
        accentColor: ACCENT_COLOR_MAP[category] ?? undefined,
        isFeatured: project.featured_on_portfolio,
        featuredOnHome: project.featured_on_home,
        featuredOnPortfolio: project.featured_on_portfolio,
        videoPreview: toVideoPreview(gallery),
        landingPageSlug: project.landing_page?.slug
    };
}
function mapStaticProjectToPortfolioProject(project, index) {
    const type = determineProjectType(project);
    const layout = buildLayout(type, index);
    const category = getProjectCategory(project.category);
    const tags = toTagsList(project.tags);
    const detail = {
        description: project.title,
        highlights: tags.slice(0, 3),
        gallery: project.img ? [
            project.img
        ] : []
    };
    return {
        id: `static-${project.id}`,
        slug: project.slug,
        title: project.title,
        subtitle: project.client,
        client: project.client,
        category,
        displayCategory: project.category,
        tags,
        year: project.year,
        image: project.img || '',
        type,
        layout,
        detail,
        accentColor: ACCENT_COLOR_MAP[category] ?? undefined,
        isFeatured: true,
        featuredOnHome: true,
        featuredOnPortfolio: true,
        videoPreview: undefined,
        landingPageSlug: undefined
    };
}
}),
"[project]/src/lib/supabase/static.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "createStaticClient",
    ()=>createStaticClient
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f2e$pnpm$2f40$supabase$2b$supabase$2d$js$40$2$2e$93$2e$1$2f$node_modules$2f40$supabase$2f$supabase$2d$js$2f$dist$2f$index$2e$mjs__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$locals$3e$__ = __turbopack_context__.i("[project]/node_modules/.pnpm/@supabase+supabase-js@2.93.1/node_modules/@supabase/supabase-js/dist/index.mjs [app-rsc] (ecmascript) <locals>");
;
function createStaticClient() {
    if (process.env.PLAYWRIGHT_TEST) {
        const mockQuery = {
            eq: ()=>mockQuery,
            order: ()=>mockQuery,
            limit: ()=>mockQuery,
            returns: ()=>Promise.resolve({
                    data: [],
                    error: null
                }),
            select: ()=>mockQuery,
            single: ()=>Promise.resolve({
                    data: null,
                    error: null
                })
        };
        return {
            from: ()=>mockQuery,
            storage: {
                from: ()=>({
                        getPublicUrl: ()=>({
                                data: {
                                    publicUrl: ''
                                }
                            })
                    })
            }
        };
    }
    const supabaseUrl = ("TURBOPACK compile-time value", "https://umkmwbkwvulxtdodzmzf.supabase.co");
    const supabaseKey = ("TURBOPACK compile-time value", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVta213Ymt3dnVseHRkb2R6bXpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgzNDE4MzcsImV4cCI6MjA4MzkxNzgzN30.wssvD9W-yzRyLpq8aMCw57E4wNz7OnQ58ujLzYmF6CA") ?? ("TURBOPACK compile-time value", "sb_publishable_lW8dC02qgDYiYxBfHGr54A_X1-D-NQ4");
    if ("TURBOPACK compile-time falsy", 0) //TURBOPACK unreachable
    ;
    return (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f2e$pnpm$2f40$supabase$2b$supabase$2d$js$40$2$2e$93$2e$1$2f$node_modules$2f40$supabase$2f$supabase$2d$js$2f$dist$2f$index$2e$mjs__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$locals$3e$__["createClient"])(supabaseUrl, supabaseKey, {
        auth: {
            persistSession: false
        }
    });
}
}),
"[project]/src/config/content.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "ABOUT_CONTENT",
    ()=>ABOUT_CONTENT,
    "HOME_CONTENT",
    ()=>HOME_CONTENT,
    "PORTFOLIO_CONTENT",
    ()=>PORTFOLIO_CONTENT,
    "TAG_CATALOG",
    ()=>TAG_CATALOG
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$supabase$2f$urls$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/lib/supabase/urls.ts [app-rsc] (ecmascript)");
;
const siteAsset = (path)=>(0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$supabase$2f$urls$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["buildSupabaseStorageUrl"])('site-assets', path);
const projectMedia = (path)=>(0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$supabase$2f$urls$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["buildSupabaseStorageUrl"])('portfolio-media', path);
const projectVideo = (path)=>(0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$supabase$2f$urls$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["buildSupabaseStorageUrl"])('project-videos', path);
const HOME_CONTENT = {
    hero: {
        tag: '[BRAND AWARENESS]',
        // Otimizado: Array permite animação escalonada (stagger) linha a linha
        title: [
            'Você não vê o design.'
        ],
        subtitle: 'Mas ele vê você.',
        cta: 'step inside'
    },
    showcase: {
        title: 'portfólio showcase',
        floatingLabel: '[what we love working on]',
        cta: {
            label: 'let’s build something great →',
            href: '/#contact'
        },
        ctas: [
            {
                label: 'Fale Comigo',
                href: '#contact',
                variant: 'primary'
            },
            {
                label: 'Download CV',
                href: '/cv-danilo-novais.pdf',
                variant: 'secondary',
                download: true,
                external: true
            }
        ],
        categories: [
            {
                id: 'brand-campaigns',
                label: 'Brand & Campaigns',
                titleDesktop: 'Brand & Campaigns',
                // Otimizado: Quebra forçada para evitar viúva em mobile pequeno
                titleMobile: 'Brand &\nCampaigns',
                align: 'end',
                thumb: siteAsset('home/showcase/Branding-Project.webp')
            },
            {
                id: 'videos-motions',
                label: 'Videos & Motion',
                titleDesktop: 'Videos & Motion',
                titleMobile: 'Videos &\nMotion',
                align: 'center',
                thumb: siteAsset('home/showcase/Key-Visual.webp')
            },
            {
                id: 'websites-webcampaigns-tech',
                label: 'Web Campaigns, Websites & Tech',
                // Otimizado: Balanceamento visual para desktop
                titleDesktop: 'Web Campaigns,\nWebsites & Tech',
                // Otimizado: Quebra estratégica para mobile (3 linhas equilibradas)
                titleMobile: 'Web Campaigns,\nWebsites & Tech',
                align: 'start',
                thumb: siteAsset('home/showcase/webdesigner-2.gif')
            }
        ]
    },
    featuredProjects: [
        {
            id: 1,
            slug: 'magic-radio-branding',
            title: 'Magic — devolvendo a magia ao rádio',
            category: 'branding & campanha',
            client: 'Magic',
            year: 2023,
            tags: [
                'Branding',
                'Campaign'
            ],
            img: projectMedia('projects/creative-direction/hero.webp'),
            layout: {
                // Otimizado: 'min-h' previne overflow de texto, 'aspect' mantém proporção visual
                h: 'min-h-[400px] md:h-[500px] aspect-[4/5] md:aspect-auto',
                cols: 'md:col-span-5',
                sizes: '(max-width: 1024px) 100vw, 42vw'
            }
        },
        {
            id: 2,
            slug: 'branding-project-01',
            title: 'Uma marca ousada e consistente',
            category: 'Branding',
            client: 'Cliente confidencial',
            year: 2022,
            tags: [
                'Strategy',
                'Identity'
            ],
            img: projectMedia('projects/campaign/hero.webp'),
            layout: {
                h: 'min-h-[400px] md:h-[500px] aspect-[4/5] md:aspect-auto',
                cols: 'md:col-span-7',
                sizes: '(max-width: 1024px) 100vw, 58vw'
            }
        },
        {
            id: 3,
            slug: 'key-visual-campaign',
            title: 'Key visual para campanha sazonal',
            category: 'Campanha',
            client: 'Cliente confidencial',
            year: 2021,
            tags: [
                'Art Direction'
            ],
            img: projectMedia('projects/key-vision/gallery/converted-5-webp.webp'),
            layout: {
                // Otimizado: Altura maior para destaque full-width
                h: 'min-h-[400px] md:h-[600px]',
                cols: 'md:col-span-12',
                sizes: '100vw'
            }
        },
        {
            id: 4,
            slug: 'webdesigner-motion',
            title: 'Experiência web em movimento',
            category: 'Web & Motion',
            client: 'Cliente confidencial',
            year: 2023,
            tags: [
                'UX/UI',
                'Animation'
            ],
            img: projectMedia('projects/key_vision/hero.webp'),
            layout: {
                h: 'min-h-[400px] md:h-[400px] aspect-video md:aspect-auto',
                cols: 'md:col-span-8',
                sizes: '(max-width: 1024px) 100vw, 66vw'
            }
        }
    ],
    clients: {
        title: 'marcas com as quais já trabalhei',
        logos: Array.from({
            length: 12
        }, (_, i)=>({
                id: i + 1,
                src: siteAsset(`clients/clients.strip.${i + 1}.svg`),
                alt: `Logo do cliente ${i + 1}`
            }))
    },
    contact: {
        title: 'contato',
        subtitle: 'Tem uma pergunta ou quer trabalhar junto?'
    }
};
const TAG_CATALOG = [
    {
        category: {
            label: 'Videos & Motions',
            slug: 'videos-motions',
            type: 'category'
        },
        tags: [
            {
                label: 'Vídeo',
                slug: 'video',
                type: 'tag'
            },
            {
                label: 'Vídeo Institucional',
                slug: 'brand-video',
                type: 'tag'
            },
            {
                label: 'Vídeo para Redes Sociais',
                slug: 'social-video',
                type: 'tag'
            },
            {
                label: 'Filme Publicitário',
                slug: 'advertising-video',
                type: 'tag'
            },
            {
                label: 'Edição de Vídeo',
                slug: 'video-editing',
                type: 'tag'
            },
            {
                label: 'Motion Design',
                slug: 'motion-design',
                type: 'tag'
            },
            {
                label: 'Animação',
                slug: 'animation',
                type: 'tag'
            },
            {
                label: 'Animação 2D',
                slug: '2d-animation',
                type: 'tag'
            },
            {
                label: 'Tipografia Cinética',
                slug: 'kinetic-typography',
                type: 'tag'
            },
            {
                label: 'Transições Animadas',
                slug: 'animated-transitions',
                type: 'tag'
            },
            {
                label: 'Microinterações',
                slug: 'micro-interactions',
                type: 'tag'
            },
            {
                label: 'Narrativa Visual',
                slug: 'visual-storytelling',
                type: 'tag'
            },
            {
                label: 'Roteiro',
                slug: 'script',
                type: 'tag'
            },
            {
                label: 'Conceito de Vídeo',
                slug: 'video-concept',
                type: 'tag'
            },
            {
                label: 'Design de Som',
                slug: 'sound-design',
                type: 'tag'
            }
        ]
    }
];
const ABOUT_CONTENT = {
    hero: {
        title: {
            text: 'Sou ',
            highlight: 'Danilo Novais. '
        },
        manifesto: [
            {
                text: 'Você ',
                highlight: 'não vê tudo ',
                textEnd: 'o que eu faço.'
            },
            {
                text: 'Mas sente '
            },
            {
                text: 'quando ',
                highlight: 'funciona.'
            }
        ],
        description: [
            'Crio designs que observam,\n',
            'entendem e guiam experiências com intenção,\n',
            'estratégia e tecnologia,\n na medida exata.'
        ],
        videos: {
            desktop: siteAsset('about/hero/about.hero.desktop_video.mp4'),
            mobile: siteAsset('about/hero/about.hero.mobile_video.mp4')
        }
    },
    beliefsIntro: [
        {
            text: 'Acredito no '
        },
        {
            text: 'design que muda o dia',
            highlight: true
        },
        {
            text: ' de alguém.',
            newLine: true
        },
        {
            text: 'Não pelo choque, '
        },
        {
            text: 'mas pela conexão.',
            highlight: true
        }
    ],
    intro: {
        origin: 'Goiânia, 2012. O início foi em agências, mas a inquietude era maior.'
    },
    origin: {
        title: 'Origem',
        blocks: [
            {
                type: 'block',
                id: '1',
                title: 'O QUE PERMANECE',
                text: 'Desde cedo, sempre prestei atenção no que ficava — não só no que aparecia. Enquanto muitos olhavam para o brilho imediato, eu era atraído pelos vestígios, pelos detalhes que sobreviviam ao tempo. A essência das coisas sempre falou mais alto do que a superfície.',
                description: '',
                src: siteAsset('about/origin/about.origin_image.1.webp'),
                alt: 'Observando os detalhes',
                align: 'right'
            },
            {
                type: 'block',
                id: '2',
                title: 'DO TRAÇO À INTENÇÃO',
                text: 'Rabiscos viraram ideias. Ideias viraram projetos. E os projetos começaram a deixar rastros. Meu processo criativo nasceu do improviso, do lápis na margem do caderno. Aos poucos, aquilo que era instinto virou direção. Com cada tentativa, aprendi a dar forma ao invisível — até que os conceitos começaram a falar por si.',
                description: '',
                src: siteAsset('about/origin/about.origin_image.2.webp'),
                alt: 'Processo criativo',
                align: 'left'
            },
            {
                type: 'block',
                id: '3',
                title: 'A DESCOBERTA DO INVISÍVEL',
                text: 'Foi ali que entendi: design não é enfeite. É ferramenta invisível de transformação. Por trás de cada escolha visual, existe intenção. Descobri que o design verdadeiro não grita — ele conduz. Ele está presente nos detalhes que ninguém percebe, mas que todos sentem. Transformar sem que se perceba a transformação: isso é potência.',
                description: '',
                src: siteAsset('about/origin/about.origin_image.3.webp'),
                alt: 'Design invisível',
                align: 'right'
            },
            {
                type: 'block',
                id: '4',
                title: 'EXPANSÃO COM PROPÓSITO',
                text: 'Estudei Comunicação, mergulhei no design, no branding e hoje uso inteligência artificial para expandir o alcance sem perder a essência humana da criação. Minha trajetória uniu intuição com método, arte com estratégia. O futuro pede novas ferramentas — e eu as abracei. Mas nunca deixei que a tecnologia apagasse o que me move: a sensibilidade, o olhar atento, a busca pelo significado.',
                description: '',
                src: siteAsset('about/origin/about.origin_image.4.webp'),
                alt: 'Expansão e tecnologia',
                align: 'left'
            }
        ]
    },
    whatIDo: {
        title: [
            'Do insight ao impacto.',
            'Mesmo quando você não percebe.'
        ],
        cards: [
            {
                id: '1',
                text: 'Direção criativa que organiza o caos'
            },
            {
                id: '2',
                text: 'Design estratégico que guia decisões'
            },
            {
                id: '3',
                text: 'Identidades que permanecem na memória'
            },
            {
                id: '4',
                text: 'Campanhas multicanais com lógica e emoção'
            },
            {
                id: '5',
                text: 'Branding que não grita, mas marca'
            },
            {
                id: '6',
                text: 'Inteligência Artificial aplicada à criação'
            },
            {
                id: '7',
                text: 'Liderança Criativa com visão e método'
            }
        ],
        marquee: [
            'DIREÇÃO CRIATIVA',
            'DESIGN ESTRATÉGICO',
            'IDENTIDADES',
            'CAMPANHAS',
            'BRANDING',
            'INTELIGÊNCIA ARTIFICIAL',
            'LIDERANÇA CRIATIVA'
        ]
    },
    method: {
        title: [
            'Criatividade com método.',
            'Impacto sem ruído.'
        ],
        videos: {
            desktop: siteAsset('about/method/about.method.desktop_video.mp4'),
            mobile: siteAsset('about/method/about.method.mobile_video.mp4')
        },
        intro: [
            'Antes da estética, existe intenção.',
            'Antes do layout, existe lógica.',
            'Antes do impacto, existe silêncio.'
        ],
        steps: [
            {
                id: '01',
                text: 'Briefings bem construídos para decisões claras'
            },
            {
                id: '02',
                text: 'Estratégia como base de qualquer criação'
            },
            {
                id: '03',
                text: 'Design com propósito, não só beleza'
            },
            {
                id: '04',
                text: 'Revisões inteligentes, sem ruído desnecessário'
            },
            {
                id: '05',
                text: 'IA e automações para escalar com qualidade'
            },
            {
                id: '06',
                text: 'Métricas criativas: engajamento, retenção e resultado'
            }
        ]
    },
    beliefs: [
        {
            text: 'Um vídeo que respira.',
            highlight: 'respira'
        },
        {
            text: 'Uma marca que se reconhece.',
            highlight: 'reconhece'
        },
        {
            text: 'Um detalhe que fica.',
            highlight: 'fica'
        },
        {
            text: 'Crio para gerar presença.',
            highlight: 'Crio'
        },
        {
            text: 'Mesmo quando não estou ali.',
            highlight: 'Mesmo'
        },
        {
            text: 'Mesmo quando ninguém percebe o esforço.',
            highlight: 'Mesmo'
        }
    ],
    closing: {
        title: 'Hoje sou Diretor de Criação, com mais de 10 anos de estrada.',
        text: [
            'Já liderei marcas, agências, eventos e criei experiências para todos os canais.',
            'Agora, quero criar algo que permaneça — com você.'
        ],
        ghostText: {
            prefix: 'ISSO É',
            main: 'GHOST DESIGN'
        },
        ctas: [
            {
                label: 'Fale Comigo',
                href: '#contact',
                variant: 'primary'
            },
            {
                label: 'Download CV',
                href: '/cv-danilo-novais.pdf',
                variant: 'secondary',
                download: true,
                external: true
            }
        ]
    }
};
const PORTFOLIO_CONTENT = {
    hero: {
        video: {
            desktop: projectVideo('VIDEO-APRESENTACAO-PORTFOLIO.mp4'),
            mobile: projectVideo('VIDEO-APRESENTACAO-PORTFOLIO.mp4')
        }
    }
};
}),
"[project]/src/app/portfolio/page.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "default",
    ()=>PortfolioPage,
    "metadata",
    ()=>metadata,
    "revalidate",
    ()=>revalidate
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f2e$pnpm$2f$next$40$16$2e$1$2e$5_$40$babel$2b$core$40$7$2e$28$2e$6_$40$opentelemetry$2b$api$40$1$2e$9$2e$0_$40$playwright$2b$test$40$1$2e$58$2e$0_react$2d$d_da4cc879827f7917e183558a349a788d$2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/.pnpm/next@16.1.5_@babel+core@7.28.6_@opentelemetry+api@1.9.0_@playwright+test@1.58.0_react-d_da4cc879827f7917e183558a349a788d/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-jsx-dev-runtime.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$app$2f$portfolio$2f$PortfolioClient$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/app/portfolio/PortfolioClient.tsx [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$supabase$2f$queries$2f$projects$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/lib/supabase/queries/projects.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$portfolio$2f$project$2d$mappers$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/lib/portfolio/project-mappers.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$supabase$2f$static$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/lib/supabase/static.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$config$2f$content$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/config/content.ts [app-rsc] (ecmascript)");
;
;
;
;
;
;
const revalidate = 60;
const metadata = {
    title: 'Portfólio',
    description: 'Explore uma seleção curada de projetos de Branding, Motion Design e Creative Development.'
};
const FALLBACK_CATEGORY_MAP = {
    'branding & campanha': 'branding',
    branding: 'branding',
    campanha: 'campanha',
    'web & motion': 'web',
    'web & digital': 'web',
    'motion & video': 'motion',
    'video & motion': 'motion',
    'motion': 'motion',
    'videos & motions': 'motion'
};
function mapFallbackCategory(label) {
    if (!label) return 'branding';
    const normalized = label.trim().toLowerCase();
    return FALLBACK_CATEGORY_MAP[normalized] ?? 'branding';
}
function buildFallbackProjects() {
    return (__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$config$2f$content$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["HOME_CONTENT"].featuredProjects ?? []).map((project, index)=>{
        const layout = project.layout ?? {};
        const category = mapFallbackCategory(project.category);
        return {
            id: `fallback-${project.id ?? index}`,
            slug: project.slug ?? `fallback-${index}`,
            title: project.title ?? 'Projeto de portfólio',
            subtitle: project.category,
            client: project.client ?? 'Cliente confidencial',
            category,
            displayCategory: project.category ?? 'Projeto',
            tags: project.tags ?? [],
            year: typeof project.year === 'number' ? project.year : Number(project.year) || new Date().getFullYear(),
            image: project.img || '',
            type: index < 4 ? 'A' : 'B',
            layout: {
                cols: layout.cols ?? 'md:col-span-4',
                height: layout.h ?? 'min-h-[320px]',
                aspectRatio: layout.aspect ?? layout.aspectRatio,
                sizes: layout.sizes
            },
            detail: {
                description: project.title ?? 'Projeto de portfólio',
                highlights: project.tags
            },
            accentColor: category === 'branding' ? '#0057ff' : category === 'campanha' ? '#ff3366' : undefined,
            featuredOnPortfolio: true
        };
    });
}
async function PortfolioPage() {
    let projects = [];
    try {
        const hasSupabaseEnv = Boolean(("TURBOPACK compile-time value", "https://umkmwbkwvulxtdodzmzf.supabase.co")) && Boolean(("TURBOPACK compile-time value", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVta213Ymt3dnVseHRkb2R6bXpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgzNDE4MzcsImV4cCI6MjA4MzkxNzgzN30.wssvD9W-yzRyLpq8aMCw57E4wNz7OnQ58ujLzYmF6CA") ?? ("TURBOPACK compile-time value", "sb_publishable_lW8dC02qgDYiYxBfHGr54A_X1-D-NQ4"));
        if (hasSupabaseEnv) {
            const supabase = (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$supabase$2f$static$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["createStaticClient"])();
            const dbProjects = await (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$supabase$2f$queries$2f$projects$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["listProjects"])({}, supabase);
            projects = dbProjects.map((project, index)=>(0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$portfolio$2f$project$2d$mappers$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["mapDbProjectToPortfolioProject"])(project, index));
        } else {
            console.warn('[Portfolio] Supabase env vars missing, using fallback projects.');
            projects = buildFallbackProjects();
        }
    } catch (error) {
        console.error('[Portfolio] Error occurred:', error instanceof Error ? error.message : error);
        projects = buildFallbackProjects();
    }
    return /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f2e$pnpm$2f$next$40$16$2e$1$2e$5_$40$babel$2b$core$40$7$2e$28$2e$6_$40$opentelemetry$2b$api$40$1$2e$9$2e$0_$40$playwright$2b$test$40$1$2e$58$2e$0_react$2d$d_da4cc879827f7917e183558a349a788d$2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$app$2f$portfolio$2f$PortfolioClient$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["default"], {
        projects: projects
    }, void 0, false, {
        fileName: "[project]/src/app/portfolio/page.tsx",
        lineNumber: 111,
        columnNumber: 10
    }, this);
}
}),
"[project]/src/app/portfolio/page.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/src/app/portfolio/page.tsx [app-rsc] (ecmascript)"));
}),
];

//# sourceMappingURL=%5Broot-of-the-server%5D__47169c3f._.js.map