module.exports = [
"[project]/src/app/opengraph-image--metadata.js [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/src/app/opengraph-image--metadata.js [app-rsc] (ecmascript)"));
}),
"[externals]/next/dist/shared/lib/no-fallback-error.external.js [external] (next/dist/shared/lib/no-fallback-error.external.js, cjs)", ((__turbopack_context__, module, exports) => {

const mod = __turbopack_context__.x("next/dist/shared/lib/no-fallback-error.external.js", () => require("next/dist/shared/lib/no-fallback-error.external.js"));

module.exports = mod;
}),
"[project]/src/app/global-error.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/src/app/global-error.tsx [app-rsc] (ecmascript)"));
}),
"[project]/src/app/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/src/app/layout.tsx [app-rsc] (ecmascript)"));
}),
"[project]/src/app/template.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/src/app/template.tsx [app-rsc] (ecmascript)"));
}),
"[project]/src/app/not-found.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/src/app/not-found.tsx [app-rsc] (ecmascript)"));
}),
"[project]/src/components/layout/SiteClosure.tsx [app-rsc] (client reference proxy) <module evaluation>", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "SiteClosure",
    ()=>SiteClosure
]);
// This file is generated by next-core EcmascriptClientReferenceModule.
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f2e$pnpm$2f$next$40$16$2e$1$2e$6_$40$babel$2b$core$40$7$2e$28$2e$6_$40$opentelemetry$2b$api$40$1$2e$9$2e$0_$40$playwright$2b$test$40$1$2e$58$2e$0_react$2d$d_1d7f1e47d50ae75d5387b46423a1f17f$2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/.pnpm/next@16.1.6_@babel+core@7.28.6_@opentelemetry+api@1.9.0_@playwright+test@1.58.0_react-d_1d7f1e47d50ae75d5387b46423a1f17f/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const SiteClosure = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f2e$pnpm$2f$next$40$16$2e$1$2e$6_$40$babel$2b$core$40$7$2e$28$2e$6_$40$opentelemetry$2b$api$40$1$2e$9$2e$0_$40$playwright$2b$test$40$1$2e$58$2e$0_react$2d$d_1d7f1e47d50ae75d5387b46423a1f17f$2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call SiteClosure() from the server but SiteClosure is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/src/components/layout/SiteClosure.tsx <module evaluation>", "SiteClosure");
}),
"[project]/src/components/layout/SiteClosure.tsx [app-rsc] (client reference proxy)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "SiteClosure",
    ()=>SiteClosure
]);
// This file is generated by next-core EcmascriptClientReferenceModule.
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f2e$pnpm$2f$next$40$16$2e$1$2e$6_$40$babel$2b$core$40$7$2e$28$2e$6_$40$opentelemetry$2b$api$40$1$2e$9$2e$0_$40$playwright$2b$test$40$1$2e$58$2e$0_react$2d$d_1d7f1e47d50ae75d5387b46423a1f17f$2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/.pnpm/next@16.1.6_@babel+core@7.28.6_@opentelemetry+api@1.9.0_@playwright+test@1.58.0_react-d_1d7f1e47d50ae75d5387b46423a1f17f/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const SiteClosure = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f2e$pnpm$2f$next$40$16$2e$1$2e$6_$40$babel$2b$core$40$7$2e$28$2e$6_$40$opentelemetry$2b$api$40$1$2e$9$2e$0_$40$playwright$2b$test$40$1$2e$58$2e$0_react$2d$d_1d7f1e47d50ae75d5387b46423a1f17f$2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call SiteClosure() from the server but SiteClosure is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/src/components/layout/SiteClosure.tsx", "SiteClosure");
}),
"[project]/src/components/layout/SiteClosure.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$layout$2f$SiteClosure$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__$3c$module__evaluation$3e$__ = __turbopack_context__.i("[project]/src/components/layout/SiteClosure.tsx [app-rsc] (client reference proxy) <module evaluation>");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$layout$2f$SiteClosure$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__ = __turbopack_context__.i("[project]/src/components/layout/SiteClosure.tsx [app-rsc] (client reference proxy)");
;
__turbopack_context__.n(__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$layout$2f$SiteClosure$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__);
}),
"[project]/src/components/home/featured-projects/FeaturedProjectsSection.tsx [app-rsc] (client reference proxy) <module evaluation>", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "default",
    ()=>__TURBOPACK__default__export__
]);
// This file is generated by next-core EcmascriptClientReferenceModule.
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f2e$pnpm$2f$next$40$16$2e$1$2e$6_$40$babel$2b$core$40$7$2e$28$2e$6_$40$opentelemetry$2b$api$40$1$2e$9$2e$0_$40$playwright$2b$test$40$1$2e$58$2e$0_react$2d$d_1d7f1e47d50ae75d5387b46423a1f17f$2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/.pnpm/next@16.1.6_@babel+core@7.28.6_@opentelemetry+api@1.9.0_@playwright+test@1.58.0_react-d_1d7f1e47d50ae75d5387b46423a1f17f/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const __TURBOPACK__default__export__ = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f2e$pnpm$2f$next$40$16$2e$1$2e$6_$40$babel$2b$core$40$7$2e$28$2e$6_$40$opentelemetry$2b$api$40$1$2e$9$2e$0_$40$playwright$2b$test$40$1$2e$58$2e$0_react$2d$d_1d7f1e47d50ae75d5387b46423a1f17f$2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call the default export of [project]/src/components/home/featured-projects/FeaturedProjectsSection.tsx <module evaluation> from the server, but it's on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/src/components/home/featured-projects/FeaturedProjectsSection.tsx <module evaluation>", "default");
}),
"[project]/src/components/home/featured-projects/FeaturedProjectsSection.tsx [app-rsc] (client reference proxy)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "default",
    ()=>__TURBOPACK__default__export__
]);
// This file is generated by next-core EcmascriptClientReferenceModule.
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f2e$pnpm$2f$next$40$16$2e$1$2e$6_$40$babel$2b$core$40$7$2e$28$2e$6_$40$opentelemetry$2b$api$40$1$2e$9$2e$0_$40$playwright$2b$test$40$1$2e$58$2e$0_react$2d$d_1d7f1e47d50ae75d5387b46423a1f17f$2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/.pnpm/next@16.1.6_@babel+core@7.28.6_@opentelemetry+api@1.9.0_@playwright+test@1.58.0_react-d_1d7f1e47d50ae75d5387b46423a1f17f/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const __TURBOPACK__default__export__ = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f2e$pnpm$2f$next$40$16$2e$1$2e$6_$40$babel$2b$core$40$7$2e$28$2e$6_$40$opentelemetry$2b$api$40$1$2e$9$2e$0_$40$playwright$2b$test$40$1$2e$58$2e$0_react$2d$d_1d7f1e47d50ae75d5387b46423a1f17f$2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call the default export of [project]/src/components/home/featured-projects/FeaturedProjectsSection.tsx from the server, but it's on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/src/components/home/featured-projects/FeaturedProjectsSection.tsx", "default");
}),
"[project]/src/components/home/featured-projects/FeaturedProjectsSection.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$home$2f$featured$2d$projects$2f$FeaturedProjectsSection$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__$3c$module__evaluation$3e$__ = __turbopack_context__.i("[project]/src/components/home/featured-projects/FeaturedProjectsSection.tsx [app-rsc] (client reference proxy) <module evaluation>");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$home$2f$featured$2d$projects$2f$FeaturedProjectsSection$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__ = __turbopack_context__.i("[project]/src/components/home/featured-projects/FeaturedProjectsSection.tsx [app-rsc] (client reference proxy)");
;
__turbopack_context__.n(__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$home$2f$featured$2d$projects$2f$FeaturedProjectsSection$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__);
}),
"[project]/src/components/home/hero/HomeHero.tsx [app-rsc] (client reference proxy) <module evaluation>", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "default",
    ()=>__TURBOPACK__default__export__
]);
// This file is generated by next-core EcmascriptClientReferenceModule.
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f2e$pnpm$2f$next$40$16$2e$1$2e$6_$40$babel$2b$core$40$7$2e$28$2e$6_$40$opentelemetry$2b$api$40$1$2e$9$2e$0_$40$playwright$2b$test$40$1$2e$58$2e$0_react$2d$d_1d7f1e47d50ae75d5387b46423a1f17f$2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/.pnpm/next@16.1.6_@babel+core@7.28.6_@opentelemetry+api@1.9.0_@playwright+test@1.58.0_react-d_1d7f1e47d50ae75d5387b46423a1f17f/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const __TURBOPACK__default__export__ = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f2e$pnpm$2f$next$40$16$2e$1$2e$6_$40$babel$2b$core$40$7$2e$28$2e$6_$40$opentelemetry$2b$api$40$1$2e$9$2e$0_$40$playwright$2b$test$40$1$2e$58$2e$0_react$2d$d_1d7f1e47d50ae75d5387b46423a1f17f$2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call the default export of [project]/src/components/home/hero/HomeHero.tsx <module evaluation> from the server, but it's on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/src/components/home/hero/HomeHero.tsx <module evaluation>", "default");
}),
"[project]/src/components/home/hero/HomeHero.tsx [app-rsc] (client reference proxy)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "default",
    ()=>__TURBOPACK__default__export__
]);
// This file is generated by next-core EcmascriptClientReferenceModule.
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f2e$pnpm$2f$next$40$16$2e$1$2e$6_$40$babel$2b$core$40$7$2e$28$2e$6_$40$opentelemetry$2b$api$40$1$2e$9$2e$0_$40$playwright$2b$test$40$1$2e$58$2e$0_react$2d$d_1d7f1e47d50ae75d5387b46423a1f17f$2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/.pnpm/next@16.1.6_@babel+core@7.28.6_@opentelemetry+api@1.9.0_@playwright+test@1.58.0_react-d_1d7f1e47d50ae75d5387b46423a1f17f/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const __TURBOPACK__default__export__ = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f2e$pnpm$2f$next$40$16$2e$1$2e$6_$40$babel$2b$core$40$7$2e$28$2e$6_$40$opentelemetry$2b$api$40$1$2e$9$2e$0_$40$playwright$2b$test$40$1$2e$58$2e$0_react$2d$d_1d7f1e47d50ae75d5387b46423a1f17f$2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call the default export of [project]/src/components/home/hero/HomeHero.tsx from the server, but it's on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/src/components/home/hero/HomeHero.tsx", "default");
}),
"[project]/src/components/home/hero/HomeHero.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$home$2f$hero$2f$HomeHero$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__$3c$module__evaluation$3e$__ = __turbopack_context__.i("[project]/src/components/home/hero/HomeHero.tsx [app-rsc] (client reference proxy) <module evaluation>");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$home$2f$hero$2f$HomeHero$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__ = __turbopack_context__.i("[project]/src/components/home/hero/HomeHero.tsx [app-rsc] (client reference proxy)");
;
__turbopack_context__.n(__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$home$2f$hero$2f$HomeHero$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__);
}),
"[project]/src/components/home/portfolio-showcase/PortfolioShowcase.tsx [app-rsc] (client reference proxy) <module evaluation>", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "default",
    ()=>__TURBOPACK__default__export__
]);
// This file is generated by next-core EcmascriptClientReferenceModule.
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f2e$pnpm$2f$next$40$16$2e$1$2e$6_$40$babel$2b$core$40$7$2e$28$2e$6_$40$opentelemetry$2b$api$40$1$2e$9$2e$0_$40$playwright$2b$test$40$1$2e$58$2e$0_react$2d$d_1d7f1e47d50ae75d5387b46423a1f17f$2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/.pnpm/next@16.1.6_@babel+core@7.28.6_@opentelemetry+api@1.9.0_@playwright+test@1.58.0_react-d_1d7f1e47d50ae75d5387b46423a1f17f/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const __TURBOPACK__default__export__ = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f2e$pnpm$2f$next$40$16$2e$1$2e$6_$40$babel$2b$core$40$7$2e$28$2e$6_$40$opentelemetry$2b$api$40$1$2e$9$2e$0_$40$playwright$2b$test$40$1$2e$58$2e$0_react$2d$d_1d7f1e47d50ae75d5387b46423a1f17f$2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call the default export of [project]/src/components/home/portfolio-showcase/PortfolioShowcase.tsx <module evaluation> from the server, but it's on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/src/components/home/portfolio-showcase/PortfolioShowcase.tsx <module evaluation>", "default");
}),
"[project]/src/components/home/portfolio-showcase/PortfolioShowcase.tsx [app-rsc] (client reference proxy)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "default",
    ()=>__TURBOPACK__default__export__
]);
// This file is generated by next-core EcmascriptClientReferenceModule.
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f2e$pnpm$2f$next$40$16$2e$1$2e$6_$40$babel$2b$core$40$7$2e$28$2e$6_$40$opentelemetry$2b$api$40$1$2e$9$2e$0_$40$playwright$2b$test$40$1$2e$58$2e$0_react$2d$d_1d7f1e47d50ae75d5387b46423a1f17f$2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/.pnpm/next@16.1.6_@babel+core@7.28.6_@opentelemetry+api@1.9.0_@playwright+test@1.58.0_react-d_1d7f1e47d50ae75d5387b46423a1f17f/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const __TURBOPACK__default__export__ = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f2e$pnpm$2f$next$40$16$2e$1$2e$6_$40$babel$2b$core$40$7$2e$28$2e$6_$40$opentelemetry$2b$api$40$1$2e$9$2e$0_$40$playwright$2b$test$40$1$2e$58$2e$0_react$2d$d_1d7f1e47d50ae75d5387b46423a1f17f$2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call the default export of [project]/src/components/home/portfolio-showcase/PortfolioShowcase.tsx from the server, but it's on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/src/components/home/portfolio-showcase/PortfolioShowcase.tsx", "default");
}),
"[project]/src/components/home/portfolio-showcase/PortfolioShowcase.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$home$2f$portfolio$2d$showcase$2f$PortfolioShowcase$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__$3c$module__evaluation$3e$__ = __turbopack_context__.i("[project]/src/components/home/portfolio-showcase/PortfolioShowcase.tsx [app-rsc] (client reference proxy) <module evaluation>");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$home$2f$portfolio$2d$showcase$2f$PortfolioShowcase$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__ = __turbopack_context__.i("[project]/src/components/home/portfolio-showcase/PortfolioShowcase.tsx [app-rsc] (client reference proxy)");
;
__turbopack_context__.n(__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$home$2f$portfolio$2d$showcase$2f$PortfolioShowcase$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__);
}),
"[project]/src/components/home/hero/VideoManifesto.tsx [app-rsc] (client reference proxy) <module evaluation>", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "VideoManifesto",
    ()=>VideoManifesto
]);
// This file is generated by next-core EcmascriptClientReferenceModule.
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f2e$pnpm$2f$next$40$16$2e$1$2e$6_$40$babel$2b$core$40$7$2e$28$2e$6_$40$opentelemetry$2b$api$40$1$2e$9$2e$0_$40$playwright$2b$test$40$1$2e$58$2e$0_react$2d$d_1d7f1e47d50ae75d5387b46423a1f17f$2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/.pnpm/next@16.1.6_@babel+core@7.28.6_@opentelemetry+api@1.9.0_@playwright+test@1.58.0_react-d_1d7f1e47d50ae75d5387b46423a1f17f/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const VideoManifesto = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f2e$pnpm$2f$next$40$16$2e$1$2e$6_$40$babel$2b$core$40$7$2e$28$2e$6_$40$opentelemetry$2b$api$40$1$2e$9$2e$0_$40$playwright$2b$test$40$1$2e$58$2e$0_react$2d$d_1d7f1e47d50ae75d5387b46423a1f17f$2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call VideoManifesto() from the server but VideoManifesto is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/src/components/home/hero/VideoManifesto.tsx <module evaluation>", "VideoManifesto");
}),
"[project]/src/components/home/hero/VideoManifesto.tsx [app-rsc] (client reference proxy)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "VideoManifesto",
    ()=>VideoManifesto
]);
// This file is generated by next-core EcmascriptClientReferenceModule.
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f2e$pnpm$2f$next$40$16$2e$1$2e$6_$40$babel$2b$core$40$7$2e$28$2e$6_$40$opentelemetry$2b$api$40$1$2e$9$2e$0_$40$playwright$2b$test$40$1$2e$58$2e$0_react$2d$d_1d7f1e47d50ae75d5387b46423a1f17f$2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/.pnpm/next@16.1.6_@babel+core@7.28.6_@opentelemetry+api@1.9.0_@playwright+test@1.58.0_react-d_1d7f1e47d50ae75d5387b46423a1f17f/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const VideoManifesto = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f2e$pnpm$2f$next$40$16$2e$1$2e$6_$40$babel$2b$core$40$7$2e$28$2e$6_$40$opentelemetry$2b$api$40$1$2e$9$2e$0_$40$playwright$2b$test$40$1$2e$58$2e$0_react$2d$d_1d7f1e47d50ae75d5387b46423a1f17f$2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call VideoManifesto() from the server but VideoManifesto is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/src/components/home/hero/VideoManifesto.tsx", "VideoManifesto");
}),
"[project]/src/components/home/hero/VideoManifesto.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$home$2f$hero$2f$VideoManifesto$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__$3c$module__evaluation$3e$__ = __turbopack_context__.i("[project]/src/components/home/hero/VideoManifesto.tsx [app-rsc] (client reference proxy) <module evaluation>");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$home$2f$hero$2f$VideoManifesto$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__ = __turbopack_context__.i("[project]/src/components/home/hero/VideoManifesto.tsx [app-rsc] (client reference proxy)");
;
__turbopack_context__.n(__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$home$2f$hero$2f$VideoManifesto$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__);
}),
"[project]/src/lib/supabase/urls.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "buildSupabaseStorageUrl",
    ()=>buildSupabaseStorageUrl,
    "getSupabaseBaseUrl",
    ()=>getSupabaseBaseUrl,
    "normalizeStoragePath",
    ()=>normalizeStoragePath,
    "validateExternalUrl",
    ()=>validateExternalUrl
]);
const normalizeUrl = (value)=>value.replace(/\/+$/, '');
function getSupabaseBaseUrl() {
    const url = ("TURBOPACK compile-time value", "https://umkmwbkwvulxtdodzmzf.supabase.co") ?? process.env.SUPABASE_URL ?? null;
    if ("TURBOPACK compile-time falsy", 0) //TURBOPACK unreachable
    ;
    try {
        return normalizeUrl(url);
    } catch  {
        return url;
    }
}
function normalizeStoragePath(filePath, bucket) {
    if (!filePath) return null;
    const bucketPrefix = bucket?.replace(/^\/+|\/+$/g, '');
    // Remove full Supabase URL prefix if present (object or render endpoints)
    let normalized = filePath.trim();
    // Clean common malformed prefixes/suffixes from backups (e.g. "file_path: ...," or quoted values)
    normalized = normalized.replace(/^file_path:\s*/i, '');
    normalized = normalized.replace(/^key:\s*/i, '');
    normalized = normalized.replace(/^"+|"+$/g, '');
    normalized = normalized.replace(/^'+|'+$/g, '');
    normalized = normalized.replace(/,+$/g, '');
    normalized = normalized.replace(/\s+$/g, '');
    normalized = normalized.replace(/^https?:\/\/[^/]+\/storage\/v1\/(?:render\/image|object)\/public\//, '');
    // Remove local /storage/v1/object/public prefix if the path was stored like that
    normalized = normalized.replace(/^\/?storage\/v1\/(?:render\/image|object)\/public\//, '');
    normalized = normalized.replace(/^\/+/, '');
    if (bucketPrefix && normalized.startsWith(`${bucketPrefix}/`)) {
        normalized = normalized.slice(bucketPrefix.length + 1);
    }
    return normalized;
}
function buildSupabaseStorageUrl(bucket, filePath) {
    if (!filePath) return null;
    const isHttp = filePath.startsWith('http://') || filePath.startsWith('https://');
    const isSupabaseUrl = filePath.includes('/storage/v1/');
    // Verifica se é uma URL externa não-Supabase
    if (isHttp && !isSupabaseUrl) {
        // Validação de segurança para URLs externas
        try {
            const url = new URL(filePath);
            // Permitir apenas protocolos seguros
            if (url.protocol !== 'https:') {
                console.warn(`Protocolo inseguro detectado: ${filePath}`);
                return null;
            }
            // Aqui poderíamos adicionar validação de domínio se necessário
            return filePath;
        } catch  {
            console.error(`URL inválida: ${filePath}`);
            return null;
        }
    }
    const cleanBucket = bucket.replace(/^\/+|\/+$/g, '');
    const normalizedPath = normalizeStoragePath(filePath, cleanBucket);
    if (!normalizedPath) {
        return filePath.startsWith('http') ? filePath : null;
    }
    // Preserva a origem caso o caminho já seja uma URL completa de outro projeto Supabase
    if (isHttp && isSupabaseUrl) {
        try {
            const url = new URL(filePath);
            const baseOrigin = `${url.protocol}//${url.host}`;
            return `${baseOrigin}/storage/v1/object/public/${cleanBucket}/${normalizedPath}`;
        } catch  {
        // se falhar, segue fluxo padrão
        }
    }
    const baseUrl = getSupabaseBaseUrl();
    if (!baseUrl) {
        return filePath.startsWith('http') ? filePath : null;
    }
    return `${baseUrl}/storage/v1/object/public/${cleanBucket}/${normalizedPath}`;
}
function validateExternalUrl(url) {
    if (!url) return null;
    const normalized = url.trim();
    if (!normalized) return null;
    const allowedProtocols = [
        'https:',
        'http:'
    ];
    try {
        const parsedUrl = new URL(normalized);
        if (allowedProtocols.includes(parsedUrl.protocol)) {
            return parsedUrl.toString();
        }
        console.warn(`Link externo inseguro bloqueado: ${url}`);
        return null;
    } catch  {
        if (normalized.startsWith('/') || normalized.startsWith('#')) {
            return normalized;
        }
        if (normalized.startsWith('//')) {
            try {
                const parsedFallback = new URL(`https:${normalized}`);
                return parsedFallback.toString();
            } catch  {
                console.error(`URL externa inválida: ${url}`);
                return null;
            }
        }
        console.error(`URL externa inválida: ${url}`);
        return null;
    }
}
}),
"[project]/src/lib/portfolio/project-mappers.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "mapDbProjectToPortfolioProject",
    ()=>mapDbProjectToPortfolioProject,
    "mapStaticProjectToPortfolioProject",
    ()=>mapStaticProjectToPortfolioProject
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$supabase$2f$urls$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/lib/supabase/urls.ts [app-rsc] (ecmascript)");
;
const CATEGORY_MAP = {
    'Branding & Identity': 'branding',
    'Campanhas & Advertising': 'campanha',
    Campanha: 'campanha',
    Branding: 'branding',
    'Web & Digital': 'web',
    'Motion & Video': 'motion',
    'Institucional & Retail': 'institucional',
    Packaging: 'packaging'
};
const ACCENT_COLOR_MAP = {
    branding: '#0057ff',
    campanha: '#ff3366',
    web: '#4fe6ff',
    motion: '#8705f2',
    institucional: '#00a868',
    packaging: '#ffd700',
    all: '#ffffff'
};
function getProjectCategory(projectType) {
    if (!projectType) return 'branding';
    const normalized = projectType.trim();
    return CATEGORY_MAP[normalized] ?? 'branding';
}
function determineProjectType(project) {
    if ('featured_on_home' in project) {
        // It's a DbProjectWithTags
        if (project.featured_on_home || project.featured_on_portfolio) {
            return 'A';
        }
    }
    // For StaticProject, or if not featured, default to 'B'
    // You might want to refine this logic based on your static data structure
    return 'B';
}
function buildLayout(projectType, index) {
    /**
   * Layout Pattern para Portfolio Grid:
   * - Rows devem sempre somar 12 colunas (edge-to-edge)
   * - Altura fixa no desktop para uniformidade visual
   * - Pattern: [5+7], [7+5], [4+4+4], [6+6], [8+4], [4+8]
   */ const pairedLayouts = [
        // Row pattern: 6 + 6 = 12 (Ensures first row is full width)
        {
            cols: 'md:col-span-6 lg:col-span-6',
            height: 'min-h-[320px]',
            aspectRatio: 'aspect-[4/5]',
            sizes: '(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 50vw'
        },
        {
            cols: 'md:col-span-6 lg:col-span-6',
            height: 'min-h-[320px]',
            aspectRatio: 'aspect-[4/5]',
            sizes: '(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 50vw'
        },
        // Row pattern: 7 + 5 = 12
        {
            cols: 'md:col-span-5 lg:col-span-7',
            height: 'min-h-[320px]',
            aspectRatio: 'aspect-[4/5]',
            sizes: '(max-width: 768px) 100vw, (max-width: 1200px) 58vw, 58vw'
        },
        {
            cols: 'md:col-span-3 lg:col-span-5',
            height: 'min-h-[320px]',
            aspectRatio: 'aspect-[4/5]',
            sizes: '(max-width: 768px) 100vw, (max-width: 1200px) 42vw, 42vw'
        },
        // Row pattern: 4 + 4 + 4 = 12 (3 cards per row)
        {
            cols: 'md:col-span-4 lg:col-span-4',
            height: 'min-h-[320px]',
            aspectRatio: 'aspect-[4/5]',
            sizes: '(max-width: 768px) 100vw, (max-width: 1200px) 33vw, 33vw'
        },
        {
            cols: 'md:col-span-4 lg:col-span-4',
            height: 'min-h-[320px]',
            aspectRatio: 'aspect-[4/5]',
            sizes: '(max-width: 768px) 100vw, (max-width: 1200px) 33vw, 33vw'
        },
        {
            cols: 'md:col-span-4 lg:col-span-4',
            height: 'min-h-[320px]',
            aspectRatio: 'aspect-[4/5]',
            sizes: '(max-width: 768px) 100vw, (max-width: 1200px) 33vw, 33vw'
        },
        // Row pattern: 6 + 6 = 12 (2 equal cards)
        {
            cols: 'md:col-span-4 lg:col-span-6',
            height: 'min-h-[320px]',
            aspectRatio: 'aspect-[4/5]',
            sizes: '(max-width: 768px) 100vw, 50vw'
        },
        {
            cols: 'md:col-span-4 lg:col-span-6',
            height: 'min-h-[320px]',
            aspectRatio: 'aspect-[4/5]',
            sizes: '(max-width: 768px) 100vw, 50vw'
        }
    ];
    // Para projetos do tipo A (featured), usar layouts variados
    // Para tipo B, usar grid uniforme de 4 colunas
    if (projectType === 'A') {
        const layoutIndex = index % pairedLayouts.length;
        return pairedLayouts[layoutIndex];
    }
    // Projetos tipo B: sempre 4 colunas (3 por linha no lg)
    return {
        cols: 'md:col-span-4 lg:col-span-4',
        height: 'min-h-[320px]',
        aspectRatio: 'aspect-[4/5]',
        sizes: '(max-width: 768px) 100vw, (max-width: 1200px) 33vw, 33vw'
    };
}
function toTagsList(tags) {
    if (!tags) return [];
    if (typeof tags[0] === 'string') {
        return tags;
    }
    return tags?.map((entry)=>entry?.tag?.label ?? entry?.tag?.slug).filter(Boolean).map((value)=>value) ?? [];
}
function createGallery(project) {
    const entries = project.gallery ?? [];
    return entries.filter((entry)=>!!entry).map((entry)=>entry.path).filter((path)=>!!path).map((path)=>(0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$supabase$2f$urls$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["buildSupabaseStorageUrl"])('portfolio-media', path)).filter((url)=>!!url); // Additional filter to remove any null urls from buildSupabaseStorageUrl
}
function toVideoPreview(galleryUrls) {
    const videoExt = [
        'mp4',
        'mov',
        'webm',
        'm4v'
    ];
    return galleryUrls.find((url)=>{
        const extension = url.split('.').pop()?.toLowerCase();
        return extension ? videoExt.includes(extension) : false;
    }) ?? undefined;
}
function mapDbProjectToPortfolioProject(project, index) {
    const type = determineProjectType(project);
    const layout = buildLayout(type, index);
    const category = getProjectCategory(project.project_type);
    const tags = toTagsList(project.tags);
    const gallery = createGallery(project);
    const thumbnailUrl = (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$supabase$2f$urls$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["buildSupabaseStorageUrl"])('portfolio-media', project.thumbnail_path ?? undefined) || (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$supabase$2f$urls$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["buildSupabaseStorageUrl"])('portfolio-media', project.hero_image_path ?? undefined);
    const detail = {
        description: project.description ?? '',
        highlights: tags.length ? tags.slice(0, 3) : undefined,
        gallery
    };
    return {
        id: project.id,
        slug: project.slug,
        title: project.title,
        subtitle: project.short_label ?? project.client_name,
        client: project.client_name,
        category,
        displayCategory: project.project_type ?? 'Web',
        tags,
        year: project.year ?? 0,
        image: thumbnailUrl || '',
        type,
        layout,
        detail,
        accentColor: ACCENT_COLOR_MAP[category] ?? undefined,
        isFeatured: project.featured_on_portfolio,
        featuredOnHome: project.featured_on_home,
        featuredOnPortfolio: project.featured_on_portfolio,
        videoPreview: toVideoPreview(gallery),
        landingPageSlug: project.landing_page?.slug
    };
}
function mapStaticProjectToPortfolioProject(project, index) {
    const type = determineProjectType(project);
    const layout = buildLayout(type, index);
    const category = getProjectCategory(project.category);
    const tags = toTagsList(project.tags);
    const detail = {
        description: project.title,
        highlights: tags.slice(0, 3),
        gallery: project.img ? [
            project.img
        ] : []
    };
    return {
        id: `static-${project.id}`,
        slug: project.slug,
        title: project.title,
        subtitle: project.client,
        client: project.client,
        category,
        displayCategory: project.category,
        tags,
        year: project.year,
        image: project.img || '',
        type,
        layout,
        detail,
        accentColor: ACCENT_COLOR_MAP[category] ?? undefined,
        isFeatured: true,
        featuredOnHome: true,
        featuredOnPortfolio: true,
        videoPreview: undefined,
        landingPageSlug: undefined
    };
}
}),
"[project]/src/lib/supabase/static.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "createStaticClient",
    ()=>createStaticClient
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f2e$pnpm$2f40$supabase$2b$supabase$2d$js$40$2$2e$93$2e$3$2f$node_modules$2f40$supabase$2f$supabase$2d$js$2f$dist$2f$index$2e$mjs__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$locals$3e$__ = __turbopack_context__.i("[project]/node_modules/.pnpm/@supabase+supabase-js@2.93.3/node_modules/@supabase/supabase-js/dist/index.mjs [app-rsc] (ecmascript) <locals>");
;
function createStaticClient() {
    if (process.env.PLAYWRIGHT_TEST) {
        const mockQuery = {
            eq: ()=>mockQuery,
            order: ()=>mockQuery,
            limit: ()=>mockQuery,
            returns: ()=>Promise.resolve({
                    data: [],
                    error: null
                }),
            select: ()=>mockQuery,
            single: ()=>Promise.resolve({
                    data: null,
                    error: null
                })
        };
        return {
            from: ()=>mockQuery,
            storage: {
                from: ()=>({
                        getPublicUrl: ()=>({
                                data: {
                                    publicUrl: ''
                                }
                            })
                    })
            }
        };
    }
    const supabaseUrl = ("TURBOPACK compile-time value", "https://umkmwbkwvulxtdodzmzf.supabase.co");
    const supabaseKey = ("TURBOPACK compile-time value", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVta213Ymt3dnVseHRkb2R6bXpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgzNDE4MzcsImV4cCI6MjA4MzkxNzgzN30.wssvD9W-yzRyLpq8aMCw57E4wNz7OnQ58ujLzYmF6CA") ?? process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY;
    if ("TURBOPACK compile-time falsy", 0) //TURBOPACK unreachable
    ;
    return (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f2e$pnpm$2f40$supabase$2b$supabase$2d$js$40$2$2e$93$2e$3$2f$node_modules$2f40$supabase$2f$supabase$2d$js$2f$dist$2f$index$2e$mjs__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$locals$3e$__["createClient"])(supabaseUrl, supabaseKey, {
        auth: {
            persistSession: false
        }
    });
}
}),
"[project]/src/app/page.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "default",
    ()=>HomePage,
    "metadata",
    ()=>metadata
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f2e$pnpm$2f$next$40$16$2e$1$2e$6_$40$babel$2b$core$40$7$2e$28$2e$6_$40$opentelemetry$2b$api$40$1$2e$9$2e$0_$40$playwright$2b$test$40$1$2e$58$2e$0_react$2d$d_1d7f1e47d50ae75d5387b46423a1f17f$2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/.pnpm/next@16.1.6_@babel+core@7.28.6_@opentelemetry+api@1.9.0_@playwright+test@1.58.0_react-d_1d7f1e47d50ae75d5387b46423a1f17f/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-jsx-dev-runtime.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$layout$2f$SiteClosure$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/components/layout/SiteClosure.tsx [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$home$2f$featured$2d$projects$2f$FeaturedProjectsSection$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/components/home/featured-projects/FeaturedProjectsSection.tsx [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$home$2f$hero$2f$HomeHero$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/components/home/hero/HomeHero.tsx [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$home$2f$portfolio$2d$showcase$2f$PortfolioShowcase$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/components/home/portfolio-showcase/PortfolioShowcase.tsx [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$home$2f$hero$2f$VideoManifesto$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/components/home/hero/VideoManifesto.tsx [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$config$2f$brand$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/config/brand.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$supabase$2f$queries$2f$projects$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/lib/supabase/queries/projects.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$portfolio$2f$project$2d$mappers$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/lib/portfolio/project-mappers.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$supabase$2f$static$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/lib/supabase/static.ts [app-rsc] (ecmascript)");
;
;
;
;
;
;
;
;
;
;
const metadata = {
    title: 'Danilo Novais | Creative Developer',
    description: 'Você não vê o design. Mas ele vê você. Portfólio de Danilo Novais - Creative Developer especializado em WebGL, R3F, Next.js e experiências digitais interativas.',
    keywords: [
        'Danilo Novais',
        'Creative Developer',
        'WebGL',
        'R3F',
        'React Three Fiber',
        'Next.js',
        'Creative Development',
        'Brazil',
        'Portfolio',
        'Interactive Design'
    ]
};
async function HomePage() {
    let featuredProjects = [];
    try {
        const supabase = (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$supabase$2f$static$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["createStaticClient"])();
        const dbProjects = await (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$supabase$2f$queries$2f$projects$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["listProjects"])({
            featuredOnHome: true
        }, supabase);
        featuredProjects = dbProjects.map((project, index)=>(0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$portfolio$2f$project$2d$mappers$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["mapDbProjectToPortfolioProject"])(project, index));
    } catch (error) {
        console.error('Error fetching projects:', error);
    // Fallback ou array vazio para evitar crash
    }
    return /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f2e$pnpm$2f$next$40$16$2e$1$2e$6_$40$babel$2b$core$40$7$2e$28$2e$6_$40$opentelemetry$2b$api$40$1$2e$9$2e$0_$40$playwright$2b$test$40$1$2e$58$2e$0_react$2d$d_1d7f1e47d50ae75d5387b46423a1f17f$2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f2e$pnpm$2f$next$40$16$2e$1$2e$6_$40$babel$2b$core$40$7$2e$28$2e$6_$40$opentelemetry$2b$api$40$1$2e$9$2e$0_$40$playwright$2b$test$40$1$2e$58$2e$0_react$2d$d_1d7f1e47d50ae75d5387b46423a1f17f$2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["Fragment"], {
        children: [
            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f2e$pnpm$2f$next$40$16$2e$1$2e$6_$40$babel$2b$core$40$7$2e$28$2e$6_$40$opentelemetry$2b$api$40$1$2e$9$2e$0_$40$playwright$2b$test$40$1$2e$58$2e$0_react$2d$d_1d7f1e47d50ae75d5387b46423a1f17f$2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$home$2f$hero$2f$HomeHero$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["default"], {}, void 0, false, {
                fileName: "[project]/src/app/page.tsx",
                lineNumber: 48,
                columnNumber: 7
            }, this),
            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f2e$pnpm$2f$next$40$16$2e$1$2e$6_$40$babel$2b$core$40$7$2e$28$2e$6_$40$opentelemetry$2b$api$40$1$2e$9$2e$0_$40$playwright$2b$test$40$1$2e$58$2e$0_react$2d$d_1d7f1e47d50ae75d5387b46423a1f17f$2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$home$2f$hero$2f$VideoManifesto$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["VideoManifesto"], {
                src: __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$config$2f$brand$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["BRAND"].assets.video.manifesto
            }, void 0, false, {
                fileName: "[project]/src/app/page.tsx",
                lineNumber: 49,
                columnNumber: 7
            }, this),
            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f2e$pnpm$2f$next$40$16$2e$1$2e$6_$40$babel$2b$core$40$7$2e$28$2e$6_$40$opentelemetry$2b$api$40$1$2e$9$2e$0_$40$playwright$2b$test$40$1$2e$58$2e$0_react$2d$d_1d7f1e47d50ae75d5387b46423a1f17f$2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$home$2f$portfolio$2d$showcase$2f$PortfolioShowcase$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["default"], {}, void 0, false, {
                fileName: "[project]/src/app/page.tsx",
                lineNumber: 50,
                columnNumber: 7
            }, this),
            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f2e$pnpm$2f$next$40$16$2e$1$2e$6_$40$babel$2b$core$40$7$2e$28$2e$6_$40$opentelemetry$2b$api$40$1$2e$9$2e$0_$40$playwright$2b$test$40$1$2e$58$2e$0_react$2d$d_1d7f1e47d50ae75d5387b46423a1f17f$2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$home$2f$featured$2d$projects$2f$FeaturedProjectsSection$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["default"], {
                projects: featuredProjects
            }, void 0, false, {
                fileName: "[project]/src/app/page.tsx",
                lineNumber: 51,
                columnNumber: 7
            }, this),
            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f2e$pnpm$2f$next$40$16$2e$1$2e$6_$40$babel$2b$core$40$7$2e$28$2e$6_$40$opentelemetry$2b$api$40$1$2e$9$2e$0_$40$playwright$2b$test$40$1$2e$58$2e$0_react$2d$d_1d7f1e47d50ae75d5387b46423a1f17f$2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$layout$2f$SiteClosure$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["SiteClosure"], {}, void 0, false, {
                fileName: "[project]/src/app/page.tsx",
                lineNumber: 52,
                columnNumber: 7
            }, this)
        ]
    }, void 0, true);
}
}),
"[project]/src/app/page.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/src/app/page.tsx [app-rsc] (ecmascript)"));
}),
];

//# sourceMappingURL=%5Broot-of-the-server%5D__a1dfc740._.js.map