ignoredBuiltDependencies:
  - '@firebase/util'
  - msw
  - protobufjs
  - re2
  - sharp
  - unrs-resolver

overrides:
  '@dataconnect/admin-generated': link:src/dataconnect-admin-generated
  '@dataconnect/generated': link:src/dataconnect-generated
