/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/media/torus_dan.glb --transform 
Files: public/media/torus_dan.glb [144.95KB] > /Users/danilonovais/_danilonov_portfolio/torus_dan-transformed.glb [67.94KB] (53%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/torus_dan-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Retopo_Cube001.geometry} material={materials['Dispersed Glass.003']} rotation={[-1.148, 0.732, 1.807]} scale={[2701.715, 2785.839, 2701.134]} />
    </group>
  )
}

useGLTF.preload('/torus_dan-transformed.glb')
