/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/assets/3d/ghost.glb --transform 
Files: public/assets/3d/ghost.glb [3.08MB] > /Users/danilonovais/_danilonov_portfolio/ghost-transformed.glb [204.64KB] (93%)
Author: Noby Grand (https://sketchfab.com/NobyGrand)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ghost-w-tophat-6b1217e3462440519a2d0e3e75bf16d3
Title: Ghost w/ Tophat
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/ghost-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Body_Ghost_White_0.geometry} material={materials.Ghost_White} position={[0, 1.558, 0]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Eyes_Eyes_0.geometry} material={materials.Eyes} position={[0, 1.558, 0]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Hat_Hat_Black_0.geometry} material={materials.Hat_Black} position={[0, 2.991, 0]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Rim_Rim_Red_0.geometry} material={materials.Rim_Red} position={[0, 2.354, 0]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/ghost-transformed.glb')
