/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: tamminen (https://sketchfab.com/tamminen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/color-orb-4d5882be5eaa4214aa394ae96563f14e
Title: Color orb
*/

import React from 'react';
import * as THREE from 'three';
import { createContext, useContext, useMemo } from 'react';
import type { ComponentProps, ComponentType, ReactNode } from 'react';
import { Merged, useGLTF } from '@react-three/drei';
import type { ThreeElements } from '@react-three/fiber';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh;
    Object_6: THREE.Mesh;
  };
  materials: {
    material: THREE.MeshPhysicalMaterial;
    material_0: THREE.MeshPhysicalMaterial;
  };
};

type InstancesContextValue = {
  Object: ComponentType<{ name: string }>;
  Object1: ComponentType<{ name: string }>;
};

const InstancesContext = createContext<InstancesContextValue | null>(null);

type InstancesProps = {
  children: ReactNode;
} & Omit<ComponentProps<typeof Merged>, 'children' | 'meshes'>;

export function Instances({ children, ...props }: InstancesProps) {
  const gltf = useGLTF('/torus_dan.glb') as unknown as GLTFResult;
  const { nodes } = gltf;
  const meshes = useMemo(
    () => ({
      Object: nodes.Object_4,
      Object1: nodes.Object_6,
    }),
    [nodes]
  );
  return (
    <Merged meshes={meshes} {...props}>
      {(mergedInstances) => (
        <InstancesContext.Provider
          value={mergedInstances as unknown as InstancesContextValue}
        >
          {children}
        </InstancesContext.Provider>
      )}
    </Merged>
  );
}

type GroupProps = ThreeElements['group'];

export function Model(props: GroupProps) {
  const instances = useContext(InstancesContext);

  if (!instances) {
    return null;
  }
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Icosphere_0">
                <instances.Object name="Object_4" />
              </group>
              <group name="Cube008_1">
                <instances.Object1 name="Object_6" />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/torus_dan.glb');
