/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/torus_dan.glb --transform 
Files: public/torus_dan.glb [96.17KB] > /Users/danilonovais/_danilonov_portfolio/torus_dan-transformed.glb [19.18KB] (80%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/torus_dan-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Retopo_Cube001.geometry} material={materials['Dispersed Glass.003']} position={[1, 1, -1]} rotation={[-1.148, 0.732, 1.807]} scale={[270.172, 278.584, 270.113]} />
    </group>
  )
}

useGLTF.preload('/torus_dan-transformed.glb')
