// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/config" | "/admin/landing-pages" | "/admin/landing-pages/[id]" | "/admin/landing-pages/new" | "/admin/login" | "/admin/midia" | "/admin/tags" | "/admin/trabalhos" | "/admin/trabalhos/[id]" | "/admin/trabalhos/new" | "/examples/supabase" | "/floating-cards" | "/instruments" | "/playground" | "/portfolio" | "/portfolio-showcase" | "/portfolio/[slug]" | "/projects/[slug]" | "/sobre"
type AppRouteHandlerRoutes = "/api/site-assets" | "/auth/callback"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/config": {}
  "/admin/landing-pages": {}
  "/admin/landing-pages/[id]": { "id": string; }
  "/admin/landing-pages/new": {}
  "/admin/login": {}
  "/admin/midia": {}
  "/admin/tags": {}
  "/admin/trabalhos": {}
  "/admin/trabalhos/[id]": { "id": string; }
  "/admin/trabalhos/new": {}
  "/api/site-assets": {}
  "/auth/callback": {}
  "/examples/supabase": {}
  "/floating-cards": {}
  "/instruments": {}
  "/playground": {}
  "/portfolio": {}
  "/portfolio-showcase": {}
  "/portfolio/[slug]": { "slug": string; }
  "/projects/[slug]": { "slug": string; }
  "/sobre": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
