/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/media/torus_dan.glb --transform 
Files: public/media/torus_dan.glb [2.81MB] > /Users/danilonovais/_danilonov_portfolio/torus_dan-transformed.glb [270.01KB] (90%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/torus_dan-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sphere002.geometry} material={materials['Dispersed Glass.003']} position={[-0.157, -0.132, -0.169]} rotation={[2.023, -0.743, -0.798]} scale={3.525} />
    </group>
  )
}

useGLTF.preload('/torus_dan-transformed.glb')
