// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/admin/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/login">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/(protected)/config/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/config">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/(protected)/config/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/(protected)/landing-pages/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/landing-pages/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/(protected)/landing-pages/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/(protected)/landing-pages/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/landing-pages/new">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/(protected)/landing-pages/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/(protected)/landing-pages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/landing-pages">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/(protected)/landing-pages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/(protected)/midia/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/midia">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/(protected)/midia/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/(protected)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/(protected)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/(protected)/tags/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/tags">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/(protected)/tags/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/(protected)/trabalhos/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/trabalhos/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/(protected)/trabalhos/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/(protected)/trabalhos/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/trabalhos/new">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/(protected)/trabalhos/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/(protected)/trabalhos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/trabalhos">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/(protected)/trabalhos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/examples/supabase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/examples/supabase">> = Specific
  const handler = {} as typeof import("../../../src/app/examples/supabase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/floating-cards/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/floating-cards">> = Specific
  const handler = {} as typeof import("../../../src/app/floating-cards/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/instruments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/instruments">> = Specific
  const handler = {} as typeof import("../../../src/app/instruments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/playground/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/playground">> = Specific
  const handler = {} as typeof import("../../../src/app/playground/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/portfolio-showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portfolio-showcase">> = Specific
  const handler = {} as typeof import("../../../src/app/portfolio-showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/portfolio/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portfolio/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/portfolio/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/portfolio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portfolio">> = Specific
  const handler = {} as typeof import("../../../src/app/portfolio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/projects/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/projects/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/sobre/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sobre">> = Specific
  const handler = {} as typeof import("../../../src/app/sobre/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/site-assets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/site-assets">> = Specific
  const handler = {} as typeof import("../../../src/app/api/site-assets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../../src/app/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/admin/(auth)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/(auth)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/(protected)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/(protected)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
