/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Noby Grand (https://sketchfab.com/NobyGrand)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ghost-w-tophat-6b1217e3462440519a2d0e3e75bf16d3
Title: Ghost w/ Tophat
*/
import * as THREE from 'three';
import React, { useEffect, useRef } from 'react';
import { useGLTF, Float } from '@react-three/drei';
import { useFrame, useThree } from '@react-three/fiber';
import { GLTF } from 'three-stdlib';
import { MotionValue } from 'framer-motion';

type GLTFResult = GLTF & {
  nodes: {
    Body_Ghost_White_0: THREE.Mesh;
    Eyes_Eyes_0: THREE.Mesh;
    Hat_Hat_Black_0: THREE.Mesh;
    Rim_Rim_Red_0: THREE.Mesh;
  };
  materials: {
    Ghost_White: THREE.MeshStandardMaterial;
    Eyes: THREE.MeshStandardMaterial;
    Hat_Black: THREE.MeshStandardMaterial;
    Rim_Red: THREE.MeshStandardMaterial;
  };
};

// Definição da interface com scrollProgress
interface GhostModelProps extends React.ComponentProps<'group'> {
  scrollProgress?: MotionValue<number>;
}

export function GhostModel({ scrollProgress, ...props }: GhostModelProps) {
  const { nodes, materials } = useGLTF(
    'https://umkmwbkwvulxtdodzmzf.supabase.co/storage/v1/object/public/site-assets/about/beliefs/ghost-transformed.glb'
  ) as unknown as GLTFResult;

  const { gl, viewport } = useThree();
  const animRef = useRef<THREE.Group>(null);
  const mouseRef = useRef({ x: 0, y: 0 });

  useEffect(() => {
    const handleMouseMove = (event: MouseEvent) => {
      if (gl.domElement) {
        const rect = gl.domElement.getBoundingClientRect();
        const x = ((event.clientX - rect.left) / rect.width) * 2 - 1;
        const y = -((event.clientY - rect.top) / rect.height) * 2 + 1;
        mouseRef.current = { x, y };
      }
    };
    const canvas = gl.domElement;
    canvas.addEventListener('mousemove', handleMouseMove);
    return () => canvas.removeEventListener('mousemove', handleMouseMove);
  }, [gl]);

  // --- Responsividade (Policy 4.3) ---
  const isMobile = viewport.width < 5;
  const baseScale = isMobile ? viewport.width * 0.18 : 0.6;

  useFrame((state) => {
    if (!animRef.current || !scrollProgress) return;

    const progress = scrollProgress.get();
    const mouse = mouseRef.current;

    // --- Animação Base (Rotação Y pelo scroll) ---
    // Aplica rotação Y baseada no scroll NO GRUPO INTERNO
    animRef.current.rotation.y = -progress * Math.PI * 2;

    // --- Resposta ao Mouse (Posição e Rotação) ---
    const mouseInfluence = 0.1;

    // Lerp positions (relativo ao 0,0,0 do grupo pai)
    animRef.current.position.x = THREE.MathUtils.lerp(
      animRef.current.position.x,
      mouse.x * mouseInfluence,
      0.05
    );
    animRef.current.position.y = THREE.MathUtils.lerp(
      animRef.current.position.y,
      mouse.y * mouseInfluence,
      0.05
    );

    // Lerp rotações X e Z baseadas no mouse (Wobble)
    animRef.current.rotation.x = THREE.MathUtils.lerp(
      animRef.current.rotation.x,
      -mouse.y * mouseInfluence * 0.5,
      0.05
    );

    // Base target para Z rotation (mouse sway)
    let targetZ = mouse.x * mouseInfluence * 0.5;
    let targetScale = 1; // Escala base interna (multiplicativa)

    // --- Efeitos de Final de Seção ---
    if (progress > 0.8) {
      const intensity = Math.min(1, (progress - 0.8) * 5);

      // Move Z para frente (aproximação)
      animRef.current.position.z = THREE.MathUtils.lerp(
        animRef.current.position.z,
        1 * intensity,
        0.05
      );

      // Adiciona wobble extra ao Z
      const timeBasedWobble =
        Math.sin(state.clock.elapsedTime * 6) * 0.1 * intensity;
      const scrollBasedWobble = (progress - 0.8) * 0.2;

      // Combina influência do mouse + efeitos finais
      targetZ += timeBasedWobble + scrollBasedWobble;

      // Aumenta escala interna (zoom effect)
      targetScale = 1 + 0.1 * intensity;
    } else {
      // Retorna Z para 0
      animRef.current.position.z = THREE.MathUtils.lerp(
        animRef.current.position.z,
        0,
        0.05
      );
    }

    // Aplica rotação Z final combinada
    animRef.current.rotation.z = THREE.MathUtils.lerp(
      animRef.current.rotation.z,
      targetZ,
      0.05
    );

    // Aplica escala interna (multiplicação sobre a escala base do grupo pai)
    animRef.current.scale.setScalar(targetScale);
  });

  return (
    <Float
      speed={2}
      rotationIntensity={0.5}
      floatIntensity={0.5}
      floatingRange={[-0.1, 0.1]}
    >
      {/* Grupo Pai: Recebe as props de posicionamento global, mas tem escala controlada responsivamente */}
      <group {...props} scale={baseScale} dispose={null}>
        {/* Grupo Interno: Recebe as animações (rotação, mouse sway) relativas ao pai */}
        <group ref={animRef}>
          <mesh
            name="Body_Ghost_White_0"
            castShadow
            receiveShadow
            geometry={nodes.Body_Ghost_White_0.geometry}
            material={materials.Ghost_White}
            position={[0, 1.5578, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            name="Eyes_Eyes_0"
            castShadow
            receiveShadow
            geometry={nodes.Eyes_Eyes_0.geometry}
            material={materials.Eyes}
            position={[0, 1.5578, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            name="Hat_Hat_Black_0"
            castShadow
            receiveShadow
            geometry={nodes.Hat_Hat_Black_0.geometry}
            material={materials.Hat_Black}
            position={[0, 2.9913, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            name="Rim_Rim_Red_0"
            castShadow
            receiveShadow
            geometry={nodes.Rim_Rim_Red_0.geometry}
            material={materials.Rim_Red}
            position={[0, 2.3541, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
        </group>
      </group>
    </Float>
  );
}

// Preload only in the browser to avoid Node/SSG environments where
// Web Workers (used by meshopt decoding) are unavailable.
if (typeof window !== 'undefined') {
  useGLTF.preload(
    'https://umkmwbkwvulxtdodzmzf.supabase.co/storage/v1/object/public/site-assets/about/beliefs/ghost-transformed.glb'
  );
}
