/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Noby Grand (https://sketchfab.com/NobyGrand)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ghost-w-tophat-6b1217e3462440519a2d0e3e75bf16d3
Title: Ghost w/ Tophat
*/

import * as THREE from 'three';
import React from 'react';
import { useGLTF, Float } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';
import { GLTF } from 'three-stdlib';
import { MotionValue } from 'framer-motion';

type GLTFResult = GLTF & {
  nodes: {
    Body_Ghost_White_0: THREE.Mesh;
    Eyes_Eyes_0: THREE.Mesh;
    Hat_Hat_Black_0: THREE.Mesh;
    Rim_Rim_Red_0: THREE.Mesh;
  };
  materials: {
    Ghost_White: THREE.MeshStandardMaterial;
    Eyes: THREE.MeshStandardMaterial;
    Hat_Black: THREE.MeshStandardMaterial;
    Rim_Red: THREE.MeshStandardMaterial;
  };
};

export function GhostModel({
  scrollProgress,
  ...props
}: React.ComponentProps<'group'> & { scrollProgress?: MotionValue<number> }) {
  // Configuração da URL exata fornecida pelo usuário
  const { nodes, materials } = useGLTF(
    'https://umkmwbkwvulxtdodzmzf.supabase.co/storage/v1/object/public/site-assets/about/beliefs/ghost-transformed.glb'
  ) as unknown as GLTFResult;

  const groupRef = React.useRef<THREE.Group>(null);

  useFrame((state) => {
    if (!groupRef.current || !scrollProgress) return;

    // Obter progresso do scroll (0 a 1)
    const progress = scrollProgress.get();

    // Rotação completa sincronizada com o scroll (360 graus / 2 * PI)
    // Multiplicamos por -2 para girar na direção 'natural' do scroll (ou ajuste conforme preferência)
    groupRef.current.rotation.y = -progress * Math.PI * 2;

    // Lógica para "movimentar mais" na última seção (progress > 0.8)
    // "ISSO É GHOST DESIGN"
    if (progress > 0.8) {
      // Intensifica a flutuação ou aproxima o modelo
      const intensity = (progress - 0.8) * 5; // 0 a 1 no final

      // Exemplo: Aproximação (Z) e leve wobble extra
      groupRef.current.position.z = THREE.MathUtils.lerp(
        groupRef.current.position.z,
        2,
        0.05
      );
      groupRef.current.rotation.z =
        Math.sin(state.clock.elapsedTime * 5) * 0.1 * intensity;
    } else {
      // Reset suave
      groupRef.current.position.z = THREE.MathUtils.lerp(
        groupRef.current.position.z,
        0,
        0.05
      );
      groupRef.current.rotation.z = THREE.MathUtils.lerp(
        groupRef.current.rotation.z,
        0,
        0.05
      );
    }
  });

  return (
    <Float
      speed={2} // Animation speed
      rotationIntensity={0.5} // Float rotation intensity
      floatIntensity={0.5} // Float height intensity
      floatingRange={[-0.1, 0.1]} // Range of y-axis values the object will float within
    >
      <group ref={groupRef} {...props} dispose={null}>
        <mesh
          name="Body_Ghost_White_0"
          castShadow
          receiveShadow
          geometry={nodes.Body_Ghost_White_0.geometry}
          material={materials.Ghost_White}
          position={[0, 1.5578, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          name="Eyes_Eyes_0"
          castShadow
          receiveShadow
          geometry={nodes.Eyes_Eyes_0.geometry}
          material={materials.Eyes}
          position={[0, 1.5578, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          name="Hat_Hat_Black_0"
          castShadow
          receiveShadow
          geometry={nodes.Hat_Hat_Black_0.geometry}
          material={materials.Hat_Black}
          position={[0, 2.9913, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          name="Rim_Rim_Red_0"
          castShadow
          receiveShadow
          geometry={nodes.Rim_Rim_Red_0.geometry}
          material={materials.Rim_Red}
          position={[0, 2.3541, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
    </Float>
  );
}

useGLTF.preload(
  'https://umkmwbkwvulxtdodzmzf.supabase.co/storage/v1/object/public/site-assets/about/beliefs/ghost-transformed.glb'
);
