# workflow.yaml - Google Antgravity Pentest Pipeline
name: 'Next.js R3F Section Pentest'
version: '1.0'

inputs:
  template_filled: string # Template preenchido
  target_section: string # "Hero3D", "Features", etc
  perf_budget: number # FPS target 60

stages:
  # STAGE 1: Parse & Generate
  - name: 'ARCHITECT_PARSE'
    agent: 'ARCHITECT'
    inputs:
      - template: '{{ inputs.template_filled }}'
    outputs:
      - raw_code: string
      - component_tree: json

  # STAGE 2: 3D Scene Parallel
  - name: '3D_RENDER'
    agent: '3D-ENGINEER'
    parallel: true
    inputs:
      - bg_elements: '{{ extract.bg_3d_elementos }}'
      - perf_target: '{{ inputs.perf_budget }}'
    outputs:
      - canvas_3d: string
      - gltf_assets: array

  # STAGE 3: Motion Design Parallel
  - name: 'MOTION_ANIMATE'
    agent: 'MOTION-DESIGNER'
    parallel: true
    inputs:
      - animations: '{{ extract.animacoes_especiais }}'
      - features_count: '{{ features.length }}'
    outputs:
      - motion_variants: string
      - gesture_handlers: string

  # STAGE 4: Integration & Type Check
  - name: 'INTEGRATE_CODE'
    agent: 'ARCHITECT'
    inputs:
      - raw_code: '{{ stage1.raw_code }}'
      - canvas_3d: '{{ stage2.canvas_3d }}'
      - motion: '{{ stage3.motion_variants }}'
    outputs:
      - full_bundle: string
      - ts_types: json

  # STAGE 5: QA Pentest Suite
  - name: 'SECURITY_QA'
    agent: 'QA-VALIDATOR'
    tests:
      - typescript: 'strict compile'
      - tailwind: 'class validation'
      - responsive: '0-4k breakpoints'
      - performance: 'Lighthouse 95+'
      - accessibility: 'WCAG AA'
      - security: 'XSS, CSP headers'
    outputs:
      - test_report: json
      - fixes_applied: boolean

  # STAGE 6: Deploy & Verify
  - name: 'DEPLOY_PREVIEW'
    agent: 'DEPLOYER'
    inputs:
      - bundle: '{{ stage4.full_bundle }}'
      - report: '{{ stage5.test_report }}'
    outputs:
      - vercel_url: string
      - bundle_size: number
      - lighthouse_score: number

summary:
  success_criteria:
    - lighthouse >= 95
    - bundle_size < 500kb
    - ts_errors = 0
    - fps_avg >= 58
  outputs:
    - live_url: '{{ stage6.vercel_url }}'
    - pentest_report: '{{ stage5.test_report }}'
    - code_bundle: '{{ stage4.full_bundle }}'
