/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
    nodes: {
        Sphere002: THREE.Mesh
    }
    materials: {
        ['Dispersed Glass.003']: THREE.MeshStandardMaterial
    }
}

export default function Model(props: React.JSX.IntrinsicElements['group']) {
    const { nodes, materials } = useGLTF('/media/torus_dan.glb') as unknown as GLTFResult
    return (
        <group {...props} dispose={null}>
            <group name="Scene">
                <mesh
                    name="Sphere002"
                    castShadow
                    receiveShadow
                    geometry={nodes.Sphere002.geometry}
                    material={materials['Dispersed Glass.003']}
                    position={[-0.2, -0.1, -0.2]}
                    rotation={[2, -0.7, -0.8]}
                    scale={3.5}
                />
            </group>
        </group>
    )
}

useGLTF.preload('/media/torus_dan.glb')
