/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef, useMemo, useContext, createContext } from 'react'
import { useGLTF, Merged } from '@react-three/drei'
import { GLTF } from 'three-stdlib'



const context = createContext()
export function Instances({ children, ...props }) {
  const { nodes } = useGLTF('/media/torus_dan.glb')
  const instances = useMemo(
    () => ({
      RetopoCube: nodes.Retopo_Cube001,
    }),
    [nodes]
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export function Model(props) {
  const instances = useContext(context)
  return (
    <group {...props} dispose={null}>
      <group>
        <instances.RetopoCube
          rotation={[-1.1484, 0.7321, 1.8072]}
          scale={[2701.7153, 2785.8389, 2701.1338]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/media/torus_dan.glb')
